# Generated by Django 4.1.5 on 2023-01-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='product',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='product',
        ),
        migrations.RemoveField(
            model_name='favorites',
            name='user',
        ),
    ]
