# Generated by Django 4.1.5 on 2023-01-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_card_product_remove_card_user_and_more'),
        ('user', '0003_remove_profile_sell_product_remove_profile_cards_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Favorites',
        ),
    ]
